export const calculatorButtons = [
    {
        primary: true,
        secondary: false,
        tertiary: false,
        singleColumn: true,
        text: "AC",
        action: "clear",
    },
    {
        primary: true,
        secondary: false,
        tertiary: false,
        singleColumn: true,
        icon: "/svg/abs.svg",
        action: "absolute",
    },
    {
        primary: true,
        secondary: false,
        tertiary: false,
        singleColumn: true,
        icon: "/svg/modulo.svg",
        action: "percentage",
    },
    {
        primary: false,
        secondary: false,
        tertiary: true,
        singleColumn: true,
        icon: "/svg/divide.svg",
        action: "division",
    }, //2nd
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: true,
        value: "1",
    },
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: true,
        value: "2",
    },
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: true,
        value: "3",
    },
    {
        primary: false,
        secondary: false,
        tertiary: true,
        singleColumn: true,
        icon: "/svg/multiplication.svg",
        action: "multiplication",
    }, //3rd
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: true,
        value: "4",
    },
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: true,
        value: "5",
    },
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: true,
        value: "6",
    },
    {
        primary: false,
        secondary: false,
        tertiary: true,
        singleColumn: true,
        icon: "/svg/minus.svg",
        action: "subtraction",
    }, //4th
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: true,
        value: "7",
    },
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: true,
        value: "8",
    },
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: true,
        value: "9",
    },
    {
        primary: false,
        secondary: false,
        tertiary: true,
        singleColumn: true,
        icon: "/svg/plus.svg",
        action: "addition",
    }, //5th
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: false,
        value: "0",
    },
    {
        primary: false,
        secondary: true,
        tertiary: false,
        singleColumn: true,
        value: ".",
    },
    {
        primary: false,
        secondary: false,
        tertiary: true,
        singleColumn: true,
        icon: "/svg/equals.svg",
        action: "equals",
    }, //6th
];
